#!/usr/bin/env ruby
require 'rubygems'
require 'mysql2'
require 'fileutils'
require 'facets/file/sanitize'
require 'yaml'


config = YAML::load_file(File.join(File.dirname(File.expand_path(__FILE__)), 'config.yml'))

VCFS_DIR = config["directories"]["contacts"] || './contacts'
ICS_DIR = config["directories"]["calendar"] || './calendar'

FileUtils.mkdir_p VCFS_DIR
FileUtils.mkdir_p ICS_DIR

def full_autocommit message='autocommit'
  `git add -A`
  `git diff --cached --exit-code`
  has_changes = $?.exitstatus != 0
  if has_changes
    system "git commit -m \"#{message}\""
  end
  has_changes
end

def sanitize name
  out = File.sanitize("#{name.gsub(/[,&%\\\/]/, '_')}").gsub(/_+/, '_')
end

client = Mysql2::Client.new(
  host: config["database"]["host"],
  username: config["database"]["username"],
  password: config["database"]["password"]
)

send_mail = false

Dir.chdir(VCFS_DIR) do
  FileUtils.rm_r(Dir.glob('*'))

  config["addressbook_ids"].each do |addressbook_id|
    rows = client.query "SELECT fullname, uri, carddata FROM #{config["database"]["database"]}.#{config["database"]["contacts_table"]} WHERE addressbookid = #{addressbook_id};"
    rows.each do |row|
      File.open(sanitize("#{row['fullname']} - #{row['uri']}"), 'wb') do |outfile|
        outfile << row["carddata"]
      end
    end
  end

  send_mail = full_autocommit
end
system "bundle exec ruby changemailer.rb \"#{VCFS_DIR}\"" if send_mail


Dir.chdir(ICS_DIR) do
  FileUtils.rm_r(Dir.glob('*'))

  config["calendar_ids"].each do |cal_id|
    rows = client.query "SELECT summary, uri, calendardata, startdate FROM #{config["database"]["database"]}.#{config["database"]["calendar_table"]} WHERE calendarid = #{cal_id};"
    rows.each do |row|
      year = row['startdate'].strftime('%Y')
      FileUtils.mkdir(year) unless File.exist? year
      File.open(File.join(year, sanitize("#{row['startdate'].strftime('%F')} #{row['summary']} - #{row['uri']}")), 'wb') do |outfile|
        outfile << row["calendardata"]
      end
    end
  end

  send_mail = full_autocommit
end
system "bundle exec ruby changemailer.rb \"#{ICS_DIR}\"" if send_mail

